name: 'Automated Cherry Pick'

on:
  pull_request:
    branches:
      - main
    types: ['closed']

env:
    IS_PR_MERGED: github.event_name == 'pull_request' && github.event.pull_request.merged
    IS_PR_LABELED_ELLIOTT: startsWith(github.event.pull_request.labels.*.name, 'elliott/')
    BRANCH_NAME: github.event.pull_request.labels.*.name

jobs:
  get_label:
   
  cherry_pick:
    name: Cherry Pick
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged
    steps:
    
      - name: Get Release Branch Name
        id: get_label
        run: node getReleaseBranch ${{ github.event.pull_request.labels.*.name }} 'elliott/'
        
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cherry pick commit
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.9
        with:
          branch: ${{ steps.get_label.outputs.branch }}
#comment for tests