name: 'Automated Cherry Pick'

on:
  pull_request:
    branches:
      - main
    types: ['closed']

jobs:
  cherry_pick:
    name: Cherry Pick
    runs-on: ubuntu-latest
    env:
      IS_PR_MERGED: github.event_name == 'pull_request' && github.event.pull_request.merged
      IS_PR_LABELED_RELEASE: startsWith(github.event.pull_request.labels.*.name, 'release/')
    if: ${{ and(IS_PR_MERGED, IS_PR_LABELED_RELEASE) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cherry pick commit
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.9
        with:
          - branch: github.event.pull_request.labels.*.name
