name: Branch check example
on: workflow_dispatch
jobs:
  check-branch:
    name: Check Branch
    runs-on: ubuntu-latest
    steps:
      - name: Terminate if branch is 'main'
        if: github.ref_name == 'main'
        run: |
          echo "Could not trigger on 'main' branch"
          exit 1
      - name: Print branch name
        run: echo "Workflow triggered on ${{ github.ref_name }}"
  
  dependent-job:
    runs-on: ubuntu-latest
    needs: check-branch
    steps:
      - run: echo "Success!"