name: Test env variables and conditionals

on:
  pull_request:
    branches:
      - main
    types: ['closed']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      IS_RELEASE_BRANCH: startsWith(github.ref, 'refs/heads/release')
      IS_MAIN_BRANCH: (github.ref == 'main')

    steps:
    - name: Check Conditionals (prev / should not run but will run)
      if: ${{ env.IS_RELEASE_BRANCH }} && ${{ env.IS_MAIN_BRANCH }}
      run: |
        echo "Check is if branch is release and branch is main"

    - name: Check Conditionals (new / should not run)
      if: ${{ env.IS_MAIN_BRANCH == 'true' }}
      run: |
        echo "Check is if branch is main ${{env.IS_MAIN_BRANCH == 'true'}}"

    - name: Check Conditionals (new / should run)
      if: ${{ env.IS_MAIN_BRANCH }} == true
      run: |
          echo "Check is if branch is main ${{ env.IS_MAIN_BRANCH }} == true"

