name: Test env variables and conditionals

on:
  pull_request:
    branches:
      - main
    types: ['closed']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      IS_RELEASE_BRANCH: startsWith(github.ref, 'refs/heads/release')
      IS_MAIN_BRANCH: (github.ref == 'main')

    steps:
    - name: Check Conditionals (prev)
      if: ${{ env.IS_RELEASE_BRANCH }} || ${{ env.IS_MAIN_BRANCH }}
      run: |
        echo "${{ env.IS_RELEASE_BRANCH }} ${{ env.IS_MAIN_BRANCH }}"
        echo "${{ github.ref }}"
        echo "${{ github.ref == 'main' }}"
        echo "${{ env.IS_MAIN_BRANCH == 'true' }}"

    - name: Check Conditionals (new)
      if: ${{ env.IS_RELEASE_BRANCH == 'true' }}
      run: |
        echo "${{ github.ref }}"
        echo "${{ github.head_ref }}"
        echo "${{ env.IS_RELEASE_BRANCH == 'true' }} ${{ env.IS_MAIN_BRANCH == 'false' }}"

    - name: Check Conditionals (new / should run)
      if: ${{ env.IS_MAIN_BRANCH == true }}
      run: |
        echo "${{ github.ref }}"
        echo "${{ github.head_ref }}"
        echo "${{ env.IS_RELEASE_BRANCH == 'true' }} ${{ env.IS_MAIN_BRANCH == 'false' }}"

